### ISSUE TITLE
About pn_cls_embeddings

### ISSUE THREAD

**Issue by King-king424** [wenxi-yue/SurgicalSAM#1]
作者您好，想向您请教个问题。
论文里说pn_cls_embeddings 不用训练，请问是为什么无需训练呢？仅通过分别加上两个随机生成的参数就能区分pos point 和 neg point，不是很理解。

**Comment by wenxixi** [comment]
Hi, 

Thank you for your interest in our work.

Regarding the positive and negative embeddings, we utilise the weights used in the original SAM rather than employing randomly initialised values. These embeddings are trained in SAM for differentiating positive and negative prompts.

**Comment by King-king424** [comment]
Thanks for the quick reply.
I have one more question.
If there are multiple target objects in an image, can your method be adapted to multi-target semantic segmentation (not instance segmentation)

**Comment by wenxixi** [comment]
Hi,

Yes, given an instrument category in the image as a prompt, our method aims to segment all instances of this instrument category in the image, regardless of the number of instances. In the main page, we have also shown some examples of our model segmenting multiple instances of the same instrument category. Please see https://github.com/wenxi-yue/SurgicalSAM#results.
