### ISSUE TITLE
The training weights have become ineffective. Please update them

### ISSUE THREAD

**Issue by puallee** [wenxi-yue/SurgicalSAM#11]
The link for training weights had ineffective, please update them.

**Comment by puallee** [comment]
In SurgicalSAM, vit_h is used.

Please find the checkpoint of SAM in vit_h version [here](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth).

We provide the checkpoint of our trained SurgicalSAM [here](https://drive.google.com/drive/folders/1i_r7hBFuzuhVBuMW0yAeHNr40TxTfWmg?usp=sharing).

**Comment by wenxi-yue** [comment]
Hi, 

We have updated the checkpoint link. Thank you for reporting the issue!
