### ISSUE TITLE
Endovis2017 inference results contain nan

### ISSUE THREAD

**Issue by Zonmgin-Zhang** [wenxi-yue/SurgicalSAM#12]
After running the inference code for Endovis 2017 with the provided checkpoint, there are some 'nan' values on the cIoU_per_class as shown below: 
![image](https://github.com/wenxi-yue/SurgicalSAM/assets/85326183/8e5f6ade-c8aa-44e6-9047-99318a862c12)
Did I choose the wrong evaluation dataset? How should I do to reproduce the results for Endovis2017 on the thesis?

**Comment by Zonmgin-Zhang** [comment]
Opps, I solved it

**Comment by wenxi-yue** [comment]
Hi, nan values indicate non-existent classes in the fold.
