### ISSUE TITLE
Can you update training set 1,2,3,？

### ISSUE THREAD

**Issue by puallee** [wenxi-yue/SurgicalSAM#13]
In your training stage， it need  training sets 1,2,3 of endovis_2018 and endovis_2017，Can you update training set 1,2,3,？

**Comment by wenxi-yue** [comment]
Hi,  

Thanks for your interest in our work. 

In our provided data, folder 0 comprises all the training data given in the dataset. We then generate various augmentations on the training data in folder 0 and store the augmented data in folders labelled from 1 to 40, each containing an augmented copy of the whole training set. You may refer to this [comment](https://github.com/wenxi-yue/SurgicalSAM/issues/9#issuecomment-1921148749) for more information. To follow our procedure, you need to download the provided data and then follow the data preprocess instructions outlined [here](https://github.com/wenxi-yue/SurgicalSAM?tab=readme-ov-file#data). This will then enable you to proceed with model training using our code.

Alternatively, you can compute SAM image embeddings online during training and conduct data augmentation online. This may require minor adjustments to the dataset code to switch to image input and incorporate specific augmentations.

**Comment by puallee** [comment]
can you provide the code for  dataset augmentations

**Comment by wenxi-yue** [comment]
Hi, 

Sorry for the late reply. 

We achieved data augmentation in this [line](https://github.com/wenxi-yue/SurgicalSAM/blob/bf5d3a8dacc3e49a7f324186da8bf0afbecc249f/surgicalSAM/tools/data_preprocess.py#L211) using the function `augmentation`. The `augmentation` function is defined [here](https://github.com/wenxi-yue/SurgicalSAM/blob/bf5d3a8dacc3e49a7f324186da8bf0afbecc249f/surgicalSAM/tools/data_preprocess.py#L17).  

Please note that we achieve data augmentation in an offline manner. If you want to conduct data augmentation online, you will need to modify the code and add the augmentation part to the dataloader.

**Comment by sunshinewuu** [comment]
Thank you for your great work!I have a question ,when When executing the dataset processing steps, this error is reported：RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 7.78 GiB total capacity; 4.60 GiB already allocated; 357.19 MiB free; 5.65 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF.
