### ISSUE TITLE
Training Codebase

### ISSUE THREAD

**Issue by summelon** [wenxi-yue/SurgicalSAM#3]
Great work!
Do you have any plan to release your training code?
We want to evaluate on our custom dataset.

**Comment by wenxi-yue** [comment]
Hi,

Thank you for your interest in our work. We will release the training code once the paper revision is complete.

**Comment by george66s** [comment]
Fantastic work!
Any chance to release the training code soon? We'd also try to work on our own dataset. Lost of thanks!

**Comment by wenxi-yue** [comment]
Hi, 

Thank you for your interest in our work. We have released the code and processed data for training.
