### ISSUE TITLE
Ablation Study

### ISSUE THREAD

**Issue by King-king424** [wenxi-yue/SurgicalSAM#4]
I'd like to know the performance difference between using sparse and dense embedding separately and using them together

**Comment by wenxi-yue** [comment]
Hi,

**Comment by wenxi-yue** [comment]
Hi, 

Thanks for your interest in our work. 

Our final results reported in the paper are obtained by using both dense and sparse prompt embeddings. 

Our ablation study results are below. 
- Method - Challenge IoU - mc IoU
- **SurgicalSAM(Ours)** - **80.33** - **58.87**
- w/o Sparse Embed. - 78.58 - 58.24
- w/o Dense Embed. - 23.61 - 14.13
