### ISSUE TITLE
What is class prototypes B

### ISSUE THREAD

**Issue by Ryanye2000** [wenxi-yue/SurgicalSAM#6]
I have a question about class prototypes B, can you tell me what is class prototype excatly

**Comment by wenxi-yue** [comment]
Hi,

Thanks for your interest in our work. The prototypes B are represented using a matrix of shape C x d, where C denotes the number of classes and d denotes feature dimension. In our case, C = 7 and d = 256. Each class prototype is just a d-dimensional vector. 

The prototypes B are obtained [here](https://github.com/wenxi-yue/SurgicalSAM/blob/f6704ddc219046471c52c39a07eb3421279e6d21/surgicalSAM/train.py#L163).
