### ISSUE TITLE
about KeyError: 'seq5\\00060_class1.png/00060.png'

### ISSUE THREAD

**Issue by Kingxudong** [wenxi-yue/SurgicalSAM#7]
In the eval_endovis function in surgicalSAM/utils.py

for file_name, prediction in endovis_masks.items():
        full_mask = gt_endovis_masks[file_name]

"KeyError: 'seq5\\00060_class1.png/00060.png'" appears
As far as I know, gt_endovis_masks: {'seq15/00000.png': is such a dictionary,
And endovis_masks: {'seq5\\00060_class1.png/00060.png' is such a dictionary
, they should not be able to correspond to，
I directly downloaded the processed endovis_2018 data set provided by you.

**Comment by wenxi-yue** [comment]
Hi,

Thanks for your interest in our work. 

The keys in your `endovis_masks` appear to have an issue; it shouldn't include "\00060_class1.png" in the middle, in your example.

Below I present the keys of `gt_endovis_masks` and `endovis_masks` for your reference. 

![image](https://github.com/wenxi-yue/SurgicalSAM/assets/142413487/1dc92ce9-bf00-44df-a371-88d6bd545596)

![image](https://github.com/wenxi-yue/SurgicalSAM/assets/142413487/3e4a065b-2528-4bdf-9b14-075134207208)
