### ISSUE TITLE
Can other instruments be identified

### ISSUE THREAD

**Issue by wjl991** [wenxi-yue/SurgicalSAM#8]
I would like to know if it is possible to identify the other instruments that are not in the dataset, except for the ones mentioned in the dataset？

**Comment by wenxi-yue** [comment]
Hi,

Thank you for your interest in our work. 

Identifying new instruments is challenging, as SurgicalSAM relies on class prototypes learned from training data. However, this may be possible if one can locate the prototype of the new instrument in the embedding space.
